###############################################
# Run GitHub's Super Linter against code base #
###############################################

---
name: GitHub's Super Linter
on: push

jobs:
  run-linters:
    name: GitHub's Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
  
      - name: Prettify code
        uses: creyD/prettier_action@master
        with:
          # run Prettier and change any code that needs fixing, before next section
          prettier_options: --write **/*.{html,css,js,md}

      - name: Run GitHub Super Linter
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
